las update

diff --git a/docker/php/DockerFile b/docker/php/DockerFile
--- a/docker/php/DockerFile
+++ b/docker/php/DockerFile
@@ -1,7 +1,15 @@
 # DockerFile
 FROM php:8.1-fpm-alpine
 
-RUN docker-php-ext-install pdo pdo_mysql
+# Useful PHP extension installer image, copy binary into your container
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
+
+# Install php extensions
+# exit on errors, exit on unset variables, print every command as it is executed
+RUN set -eux; \
+    install-php-extensions pdo pdo_mysql;
+
+# RUN docker-php-ext-install pdo pdo_mysql
 
 # allow super user - set this if you use Composer as a
 # super user at all times like in docker containers
